<a href="https://colab.research.google.com/github/Yang-jinho-engineer/github-slideshow/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3,4,5])
print(type(a1))
a2 = np.array([ [ 1,2,3], [4,5,6], [7,8,9]]) 
a3 = np.array( [ [ [ 1,2,3], [4,5,6], [7,8,9] ], [ [ 1,2,3], [4,5,6], [7,8,9] ], [ [ 1,2,3], [4,5,6], [7,8,9] ]] ) 

<class 'numpy.ndarray'>


In [ ]:
np.arange(0, 30, 2) #정수 범위로 배열 생성

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
np.linspace(0,1,5) #균등한 범위

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.logspace(0.1, 1, 20) #균등한 로그 스케일

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [ ]:
#랜덤값 
np.random.random((3,3)) #shape만 만들자 실수

array([[0.89331379, 0.35875497, 0.44172621],
       [0.98913291, 0.37596643, 0.30493033],
       [0.19455027, 0.79773476, 0.09231718]])

In [ ]:
#정규 분포, 평균, 분산
np.random.normal(0, 1, (3,3))

array([[-0.38336842, -0.08213935,  1.89016409],
       [ 0.99048186, -1.54324068, -0.40316597],
       [ 0.48621354,  0.41292635,  0.57707655]])

In [ ]:
#균등 분포
np.random.rand(3, 3)

array([[0.10354966, 0.12020816, 0.22027314],
       [0.56423039, 0.52486285, 0.53539684],
       [0.3501586 , 0.14722678, 0.30924876]])

In [ ]:
#표준 정규 분포
np.random.randn(3,3)

array([[-0.14268739,  1.32752432,  0.01581579],
       [-2.51235477,  0.64535987, -0.17696883],
       [ 1.19910632,  0.49354634,  0.96330872]])

In [ ]:
#표준 데이터 타입 bool, int, intc(c언어와 동일) uint(unsigned), float16, complex64, 
np.zeros(20, dtype=int)
np.ones((3,3), dtype=bool)
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#날짜, 시간 배열 절대적, 상대적 시간 범위
date = np.array('2020-01-01', dtype=np.datetime64) #문자열도 날짜인걸 안다
date + np.arange(12) # 01, 2,3,1까지 더한 날짜를 보여준다

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
       '2020-01-09', '2020-01-10', '2020-01-11', '2020-01-12'],
      dtype='datetime64[D]')

In [ ]:
datetime = np.datetime64('2020-06-01 12:00:12.34', 'ns') #t시간도 가능 나노시간도 하려면 'ns' 추가
datetime

numpy.datetime64('2020-06-01T12:00:12.340000000')

In [ ]:
#배열 속성 정보
def array_info(array):
  print(array)
  print("ndim:", array.ndim)
  print("shape:", array.shape)
  print("dtype:", array.dtype)
  print("size:", array.size)
  print("item size:", array.itemsize) #하나당 사이즈 int64이므로  8
  print("nbytes:", array.nbytes) #전체 바이트 크기
  print("strides:", array.strides) #다음 차원으로 넘어가기 위한... 요소가 넘어가는데 필요한 크기 

In [ ]:
array_info(a1) 

[1 2 3 4 5]
ndim: 1
shape: (5,)
dtype: int64
size: 5
item size: 8
nbytes: 40
strides: (8,)


In [ ]:
array_info(a2) #9*8 다음 축으로 넘어갈 때 8*3을 넘어가야 하므로 strides 는 24

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim: 2
shape: (3, 3)
dtype: int64
size: 9
item size: 8
nbytes: 72
strides: (24, 8)


In [ ]:
array_info(a3) # 8*9 넘어가야 다음 차원, 안에서 다음 차원으로 가려면 8*3 : bytes의 크기를 알려준다

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim: 3
shape: (3, 3, 3)
dtype: int64
size: 27
item size: 8
nbytes: 216
strides: (72, 24, 8)


In [ ]:
#indexing 배열에 대한 접근
print(a1)
print(a1[0])
print(a1[-1])
print(a1[-2]) #음수는 역으로 간다

[1 2 3 4 5]
1
5
4


In [ ]:
print(a2)
print(a2[0,-1])
print(a2[1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
5


In [ ]:
print(a3)
print(a3[1,1,1])
print(a3[2,-1,-1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
5
9


In [ ]:
#슬라이싱 a[start:stop:step]
print(a1[0:])
print(a1[:1]) #뒤에서 한개
print(a1[::2]) #2씩 뛰어서
print(a1[::-1]) #뒤에서부터 하나씩 revesre

[1 2 3 4 5]
[1]
[1 3 5]
[5 4 3 2 1]


In [ ]:
print(a2[1]) #1열만
print(a2[1, :]) #:만 있으면 all
print(a2[:2,:2]) #stop만 정의, 01, 01 1245만 출력
print(a2[1:, ::-1]) #1부터니까 456789 -1로 했으니까 reverse로 출력
print(a2[::-1,::-1]) #다 -1이면 아예 뒤집혀서 출력

[4 5 6]
[4 5 6]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
#불리언 인ㄱ덱싱(boolean indexing) 선택의 여부를 tf로 선택
print(a1)
bi = [False, True, True, False, True]
print(a1[bi]) #true인 위치 값만 출력

bi1 = np.random.randint(0,2,(3,3), dtype=bool) # 01중에 하나
print(bi1)
print(a2[bi1])

[1 2 3 4 5]
[2 3 5]
[[ True  True False]
 [ True  True  True]
 [False  True False]]
[1 2 4 5 6 8]


In [ ]:
#fancy indexing
print(a1[0], a1[2])
ind = [0,2]
print(a1[ind])
ind = np.array([[0,1],[2,0]])
print(a1[ind]) #1차원 배열에 2차원 인덱스를 넣으면 2차원으로 바뀐다

1 3
[1 3]
[[1 2]
 [3 1]]


In [ ]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row, col]) #row는0, col은 1인 2와 2,2인 9만 나온다
print(a2[row,:]) #row중 0과 2만 
print(a2[:, col]) #col 1,2만 출력
print(a2[2, col]) # 2열, 1,2번째만 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[8 9]


In [ ]:
#배열 값 삽입/수정/삭제/복사
#삽입 aixs지정 안하면 1차원 배열로 반환 , 원본 변경 없고 새로운 배열을 반환
print(a1)
b1  = np.insert(a1, 0, 10) #0번째 위치에 10을 삽입
print(b1)
print(a1)

[1 2 3 4 5]
[10  1  2  3  4  5]
[1 2 3 4 5]


In [ ]:
print(a2)
b2 = np.insert(a2,1,10,axis= 0) #축이 0이므로 
print(b2)
c2 = np.insert(a2, 1, 10, axis=1) #축이 col이 되었다
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


In [ ]:
#인덱싱으로 접근하여 수정
a1[0] = 1
print(a1)
a1[:1] = 9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[1 0 3 0 0]
[9 0 3 0 0]
[9 0 3 0 0]
[9 4 3 4 4]


In [ ]:
a2[0] = 1 #0번쨰 row다 1로 바뀜
print(a2)
a2[1:,2] = 9 #1뒤에 다 , col은 두번째 
print(a2) 
row = np.array([0,1])
col = np.array([1,2])
a2[row, col] = 0
print(a2) #특저 위치만 변경 가능

[[1 1 1]
 [4 5 9]
 [7 8 9]]
[[1 1 1]
 [4 5 9]
 [7 8 9]]
[[1 0 1]
 [4 5 0]
 [7 8 9]]


In [ ]:
#삭제 : 특정 위치 삭제, 새로운 삭제된 배열 나옴
b1 = np.delete(a1,1)
print(b1)
print(a1)

[9 3 4 4]
[9 4 3 4 4]


In [ ]:
print(a2)
b2 = np.delete(a2,1,axis=0)
print(b2)
c2 = np.delete(a2,1,axis=1)
print(c2)

[[1 0 1]
 [4 5 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


In [ ]:
#원본 배열은 안 바꾸면 속도가 더 빠르다
#배열 복사: 배열의 슬라이스는 복사본이 아니다(원본 배열에 영향을 준다, 복사를 해서 사용해야 한다)
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)
a2_sub_copy[:,1] = 1
print(a2_sub_copy)
print(a2) #1로 바뀌지 않는다

[[1 0 1]
 [4 5 0]
 [7 8 9]]
[[1 0]
 [4 5]]
[[1 1]
 [4 1]]
[[1 0 1]
 [4 5 0]
 [7 8 9]]


In [ ]:
#배열 변환
#배열 전치
print(a2)
print(a2.T) #행과 열이 바뀜
print(a3)
print(a3.T)

[[1 0 1]
 [4 5 0]
 [7 8 9]]
[[1 4 7]
 [0 5 8]
 [1 0 9]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [ ]:
#축변경
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 5 0]
 [7 8 9]]
[[1 4 7]
 [0 5 8]
 [1 0 9]]


In [ ]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2)) 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


In [ ]:
#배열의 재구조화
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3)) #2차원 배열로 변경

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#축 추가
print(n1)
print(n1[np.newaxis, :5])
print(n1[:5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [87]:
#배열 크기 변경
#배열 모양만 변경
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2) #모양만 바뀜

[[2 9 9 6 9]
 [3 8 5 8 6]]
[[2 9]
 [9 6]
 [9 3]
 [8 5]
 [8 6]]


In [88]:
#배열 크기 증가
n2.resize((5,5))
print(n2) #남는 공간은 0으로 채워짐

[[2 9 9 6 9]
 [3 8 5 8 6]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [89]:
#줄여ㅑ, 나머지 삭제
n2.resize((3,3))
print(n2)

[[2 9 9]
 [6 9 3]
 [8 5 8]]


In [90]:
#배열 추가
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3, 3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [92]:
c2 = np.append(a2, b2, axis=0)
print(c2) #2차원이 1차원으로 변형됨(axis 지정이 없으면 1차원으로 준다)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [93]:
c2 = np.append(a2, b2, axis=1) #횡으로 붙는다
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [96]:
#배열 연결, 튜플이나 리스트ㅡㄹ 인수로
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1, b1])

array([1, 3, 5, 2, 4, 6])

In [97]:
c1 = np.array([7,8,9])
np.concatenate([a1, b1, c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [100]:
a2 = np.array([[1,2,3], [4,5,6]])
np.concatenate([a2,a2]) #밑에 붙는다 axis=0
np.concatenate([a2,a2], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [101]:
#vstack([]) : 옆으로 붙는다 hstack([]) : 옆으로 
#np.dstack([]) : 깊이이므로 3차원으로 연결
#np.stack([]) : 새로운 차원으로 붙는다


In [104]:
#배열 분할
a1 = np.arange(0,10)
print(a1)
b1, c1 = np.split(a1,[5]) #5는 기준점
print(b1, c1)
b1, c1, d1, e1 ,f1 = np.split(a1, [2,4,6,8])
print(b1, c1, d1, e1 ,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


In [107]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 ,c2 = np.vsplit(a2,[2]) #2번째 줄에서 끊어짐
print(b2)
print(c2)
b2 ,c2 = np.hsplit(a2,[2]) #2번째 열에서 끊어짐
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


In [108]:
a2 = np.arange(1,28).reshape(3,3,3)
print(a2)
b2 ,c2 = np.dsplit(a2,[2]) #2번째 줄에서 끊어짐
print(b2)
print(c2)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
[[[ 1  2]
  [ 4  5]
  [ 7  8]]

 [[10 11]
  [13 14]
  [16 17]]

 [[19 20]
  [22 23]
  [25 26]]]
[[[ 3]
  [ 6]
  [ 9]]

 [[12]
  [15]
  [18]]

 [[21]
  [24]
  [27]]]


In [111]:
#배열 연산 : 벡터화 연산(벡터 연산으로 어쩌구 가능), 범용 연산 가능
#반복전 계산이 최소화, 효율적
#브로드캐스팅 : 다른 모양(혹은 차원)을 가져도 그만큼 늘어나서 계산이 가능해진다 [1,2,3] + [[1],[2],[3]]의 계산 가능
a1 = np.array([1,2,3])
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a2 + a1)

b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1 + b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [124]:
#산술연산(arithmetic operators)
a1 = np.arange(1,10)
print(a1 +1 )
print(np.add(a1,10))
print(np.subtract(a1,10))
print(-a1)
print(np.negative(a1))
print(np.multiply(a1,2))
print(np.divide(a1,2))
print(np.floor_divide(a1,2)) #// 내림연산
print(np.power(a1,2))
print(np.power(2,a1))
print(np.mod(a1,2)) #나머지 연산 %

[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[  2   4   8  16  32  64 128 256 512]
[1 0 1 0 1 0 1 0 1]


In [127]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10, size=9)
print(b1)
print(a1 + b1)
print(a1 * b1)
print(a1 /b1)
print(a1 // b1)
print(a1 **b1)
print(a1 % b1)

[1 2 3 4 5 6 7 8 9]
[6 6 9 6 4 5 2 8 9]
[ 7  8 12 10  9 11  9 16 18]
[ 6 12 27 24 20 30 14 64 81]
[0.16666667 0.33333333 0.33333333 0.66666667 1.25       1.2
 3.5        1.         1.        ]
[0 0 0 0 1 1 3 1 1]
[        1        64     19683      4096       625      7776        49
  16777216 387420489]
[1 2 3 4 1 1 1 0 0]


In [129]:
a1 = np.arange(1,10).reshape(3,3)
print(a1)
b1 = np.random.randint(1,3, size =3)
print(b1)
print(a1 + b1)
print(a1 * b1)
print(a1 /b1)
print(a1 // b1)
print(a1 **b1)
print(a1%b1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 1 2]
[[ 3  3  5]
 [ 6  6  8]
 [ 9  9 11]]
[[ 2  2  6]
 [ 8  5 12]
 [14  8 18]]
[[0.5 2.  1.5]
 [2.  5.  3. ]
 [3.5 8.  4.5]]
[[0 2 1]
 [2 5 3]
 [3 8 4]]
[[ 1  2  9]
 [16  5 36]
 [49  8 81]]
[[1 0 1]
 [0 0 0]
 [1 0 1]]


In [135]:
#절댓값
a1 = np.random.randint(-10,10,size=5)
print(a1)
print(np.absolute(a1)) #abs도 가능
#제곱, 제곱근 함수
print(np.sqrt(a1))
#지수와 로그함수
a1 = np.random.randint(1,10,size=5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))
print(np.log(a1))
print(np.log10(a1))

[ 6  8 -6 -2  0]
[6 8 6 2 0]
[2.44948974 2.82842712        nan        nan 0.        ]
[5 3 5 5 9]
[ 148.4131591    20.08553692  148.4131591   148.4131591  8103.08392758]
[ 32.   8.  32.  32. 512.]
[25  9 25 25 81]
[1.60943791 1.09861229 1.60943791 1.60943791 2.19722458]
[0.69897    0.47712125 0.69897    0.69897    0.95424251]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in sqrt
  


In [137]:
#삼각함수도 다 가능 deg2rad도 가능
t = np.linspace(0, np.pi, 3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))
x = [-1, 0, 1]
print(x)
print(np.arcsin(x))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
[-1, 0, 1]
[-1.57079633  0.          1.57079633]


In [139]:
#집계 함수 nan안전 모드도 있다(집계 함수는 숫자만 가능하므로)
a2 = np.random.randint(1,10,size=(3,3))
print(a2)
print(a2.sum(), np.sum(a2))
print(a2.sum(axis=0), np.sum(a2, axis=0)) #아래로 같은 줄들의 합
print(a2.sum(axis=1), np.sum(a2, axis=1)) #옆으로 같은 줄들의 합

[[2 8 3]
 [2 6 8]
 [3 4 2]]
38 38
[ 7 18 13] [ 7 18 13]
[13 16  9] [13 16  9]


In [140]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2, axis=0)) #아래로 같은 줄들의 누적합
print(np.cumsum(a2, axis=1)) #옆으로 같은 줄들의 누적합

[[2 8 3]
 [2 6 8]
 [3 4 2]]
[ 2 10 13 15 21 29 32 36 38]
[[ 2  8  3]
 [ 4 14 11]
 [ 7 18 13]]
[[ 2 10 13]
 [ 2  8 16]
 [ 3  7  9]]


In [142]:
print(a2)
print(np.diff(a2))
print(np.diff(a2, axis=0)) #아래로 같은 줄들의 차분
print(np.diff(a2, axis=1)) #옆으로 같은 줄들의 차분

[[2 8 3]
 [2 6 8]
 [3 4 2]]
[[ 6 -5]
 [ 4  2]
 [ 1 -2]]
[[ 0 -2  5]
 [ 1 -2 -6]]
[[ 6 -5]
 [ 4  2]
 [ 1 -2]]


In [143]:
print(a2)
print(np.prod(a2))
print(np.prod(a2, axis=0)) #아래로 같은 줄들의 내적곱
print(np.prod(a2, axis=1)) #옆으로 같은 줄들의 내적곱

[[2 8 3]
 [2 6 8]
 [3 4 2]]
110592
[ 12 192  48]
[48 96 24]


In [145]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2, axis=0)) #아래로 같은 줄들의 누적곱
print(np.cumprod(a2, axis=1)) #옆으로 같은 줄들의 누적곱

[[2 8 3]
 [2 6 8]
 [3 4 2]]
[     2     16     48     96    576   4608  13824  55296 110592]
[[  2   8   3]
 [  4  48  24]
 [ 12 192  48]]
[[ 2 16 48]
 [ 2 12 96]
 [ 3 12 24]]


In [147]:
print(a2)
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2)) #점곱, 행렬곱 (2*1 + 8 *1 + 3 * 1 = 13) 다음줄도 동일
print(np.matmul(a2,b2))

[[2 8 3]
 [2 6 8]
 [3 4 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[13 13 13]
 [16 16 16]
 [ 9  9  9]]
[[13 13 13]
 [16 16 16]
 [ 9  9  9]]


In [150]:
print(a2)
print(b2)
print(np.tensordot(a2,b2)) #그냥 dotproduct
print(np.tensordot(a2,b2,axes = 0)) #다 2, 다8, 다3
print(np.tensordot(a2,b2, axes = 1)) # dotproduct

[[2 8 3]
 [2 6 8]
 [3 4 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
38
[[[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]]


 [[[2 2 2]
   [2 2 2]
   [2 2 2]]

  [[6 6 6]
   [6 6 6]
   [6 6 6]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]


 [[[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[2 2 2]
   [2 2 2]
   [2 2 2]]]]
[[13 13 13]
 [16 16 16]
 [ 9  9  9]]


In [151]:
x = [1,2,3]
y = [4,5,6]
print(np.cross(x,y)) #벡터곱

[-3  6 -3]


In [154]:
print(a2)
print(b2)
print(np.inner(a2,b2)) #내적
print(np.outer(a2,b2)) #외적 9개씩 풀어진 형태

[[2 8 3]
 [2 6 8]
 [3 4 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[13 13 13]
 [16 16 16]
 [ 9  9  9]]
[[2 2 2 2 2 2 2 2 2]
 [8 8 8 8 8 8 8 8 8]
 [3 3 3 3 3 3 3 3 3]
 [2 2 2 2 2 2 2 2 2]
 [6 6 6 6 6 6 6 6 6]
 [8 8 8 8 8 8 8 8 8]
 [3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4]
 [2 2 2 2 2 2 2 2 2]]


In [157]:
print(a2)
print(np.mean(a2))
print(np.mean(a2, axis= 0))
print(np.mean(a2, axis=1))

[[2 8 3]
 [2 6 8]
 [3 4 2]]
4.222222222222222
[2.33333333 6.         4.33333333]
[4.33333333 5.33333333 3.        ]


In [158]:
print(a2)
print(np.std(a2))
print(np.std(a2, axis= 0))
print(np.std(a2, axis=1))

[[2 8 3]
 [2 6 8]
 [3 4 2]]
2.3465235646603193
[0.47140452 1.63299316 2.62466929]
[2.62466929 2.49443826 0.81649658]


In [159]:
print(a2)
print(np.var(a2))
print(np.var(a2, axis= 0))
print(np.var(a2, axis=1)) #min과 max도 가능하다

[[2 8 3]
 [2 6 8]
 [3 4 2]]
5.506172839506172
[0.22222222 2.66666667 6.88888889]
[6.88888889 6.22222222 0.66666667]


In [161]:
#index값도 출력할 수 있다
print(a2)
print(np.argmax(a2))
print(np.argmin(a2, axis= 0))
print(np.argmin(a2, axis=1)) 

[[2 8 3]
 [2 6 8]
 [3 4 2]]
1
[0 2 2]
[0 0 2]


In [162]:
print(a2)
print(np.median(a2))
print(np.median(a2, axis= 0)) #2 2 3의 중앙값은 2
print(np.median(a2, axis=1))  #2 8 3의 중앙값은 3

[[2 8 3]
 [2 6 8]
 [3 4 2]]
3.0
[2. 6. 3.]
[3. 6. 3.]


In [166]:
#백분위수 
a1 = np.array([0, 1, 2,3])
print(a1)
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='linear')) #선형으로 증가
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='higher')) # 0은 0 20은 1 40은 2 60도 2 80은 3 100도 3
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='lower')) # 0은 0 40은 1 60은 1 80은 2 100은 3
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='nearest')) #20은 1 40은 1 60은 2  80은 2 100은 3
print(np.percentile(a1,[0,20,40,60,80,100], interpolation='midpoint')) #20은 0.5 40은 1.5 60은 1.5 80은 2.5 100은 3

[0 1 2 3]
[0.  0.6 1.2 1.8 2.4 3. ]
[0 1 2 2 3 3]
[0 0 1 1 2 3]
[0 1 1 2 2 3]
[0.  0.5 1.5 1.5 2.5 3. ]


In [168]:
a2 = np.array([[False, False, False],[False, True, True],[False, True, True]])
print(a2)
print(np.any(a2)) #하나라도 true면 전체 true
print(np.any(a2, axis = 0)) #-0이면 아래로 FFF이니까 False, FTT니까 T, FTT니까 T
print(np.any(a2, axis = 1)) #1이면 옆으로 FFF이니까 False, FTT니까 T, 이하동일

[[False False False]
 [False  True  True]
 [False  True  True]]
True
[False  True  True]
[False  True  True]


In [171]:
a2 = np.array([[False, False, True],[True, True, True],[False, True, True]])
print(a2)
print(np.all(a2)) #다 true여야 true
print(np.all(a2, axis = 0)) #-0이면 아래로
print(np.all(a2, axis = 1))

[[False False  True]
 [ True  True  True]
 [False  True  True]]
False
[False False  True]
[False  True False]


In [178]:
#비교연산(comparison operator)
a1 = np.arange(1,10)
print(a1)
print(a1 == 5) #TF의 위치 결과값을 반환
print(a1 <= 5)
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(np.sum(a2))
print(np.count_nonzero(a2 >5)) #개수를 세줘
print(np.sum(a2 >5)) #썸이 5초과
print(np.sum(a2 >5, axis=0)) #1 4 7에서 5초과는 7 한개 
print(np.sum(a2 >5, axis=1)) # 123에서 5초과는 없음


[1 2 3 4 5 6 7 8 9]
[False False False False  True False False False False]
[ True  True  True  True  True False False False False]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
4
4
[1 1 2]
[0 1 3]


In [179]:
print(a2)
print(np.any(a2 >5)) #all도 가능
print(np.any(a2 >5, axis=0)) #1 4 7에서 5초과
print(np.any(a2 >5, axis=1)) # 123에서 5초과

[[1 2 3]
 [4 5 6]
 [7 8 9]]
True
[ True  True  True]
[False  True  True]


In [180]:
#비교 범용 함수
a1 = np.array([1,2,3,4,5])
print(a1)
b1 = np.array([1, 2, 3, 3, 4])
print(b1)
print(np.isclose(a1, b1)) #값에 따라 같은지 다른지 TF

[1 2 3 4 5]
[1 2 3 3 4]
[ True  True  True False False]


In [184]:
a1 = np.array([np.nan, 2, np.inf, 4, np.NINF])
print(a1)
print(np.isnan(a1)) 
print(np.isinf(a1))
print(np.isfinite(a1)) #무한대가 아닌 것

[ nan   2.  inf   4. -inf]
[ True False False False False]
[False False  True False  True]
[False  True False  True False]


In [187]:
a2 = np.arange(1, 10).reshape(3,3)
print(a2)
print((a2>5) & (a2<8)) #boolean 연산자
print(a2[(a2>5) & (a2<8)]) #boolean indexing

print((a2>5) | (a2<8)) #or
print(a2[(a2>5) | (a2<8)]) #or

print((a2>5) ^ (a2<8)) #or not 조건에 해당하는 67만 빼고 해당된다
print(a2[(a2>5) ^ (a2<8)]) #or not

print(~(a2>5)) #not
print(a2[~(a2>5)]) #not

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False  True]
 [ True False False]]
[6 7]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[1 2 3 4 5 6 7 8 9]
[[ True  True  True]
 [ True  True False]
 [False  True  True]]
[1 2 3 4 5 8 9]
[[ True  True  True]
 [ True  True False]
 [False False False]]
[1 2 3 4 5]


In [193]:
#배열 정렬
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.sort(a1)) #정렬
print(a1) #원본배열은 그대로
print(np.argsort(a1)) #위치값 6번인 1이 맨앞이 갔다 등등
print(a1) #원본 배열은 그대로
print(a1.sort())
print(a1)

[2 4 4 8 3 9 8 2 8 2]
[2 2 2 3 4 4 8 8 8 9]
[2 4 4 8 3 9 8 2 8 2]
[0 7 9 4 1 2 3 6 8 5]
[2 4 4 8 3 9 8 2 8 2]
None
[2 2 2 3 4 4 8 8 8 9]


In [195]:
#2차원
a2 = np.random.randint(1, 10, size= (3,3))
print(a2)
print(np.sort(a2, axis = 0)) #아래줄들끼리
print(np.sort(a2, axis = 1)) #옆으로 

[[3 4 7]
 [1 3 2]
 [2 7 2]]
[[1 3 2]
 [2 4 2]
 [3 7 7]]
[[3 4 7]
 [1 2 3]
 [2 2 7]]


In [198]:
#부분 정렬 배열에서 k개의 작은 값을 반환
a1 = np.random.randint(1, 10, size=10)
print(a1)
print(np.partition(a1,3)) #가장 작은 값 3개 주셍ㅅ 324나옴
a2 = np.random.randint(1, 10, size=(5,5))
print(a2)
print(np.partition(a2,3)) #모든 줄마다 작은 3개를 뽑아
print(np.partition(a2,3, axis = 0)) #default와 동일
print(np.partition(a2,3, axis = 1)) #col로

[8 1 9 3 3 8 2 6 7 3]
[1 3 2 3 3 8 9 6 7 8]
[[9 1 9 1 2]
 [8 7 6 9 4]
 [7 6 7 1 6]
 [6 1 2 2 1]
 [7 3 1 5 2]]
[[1 2 1 9 9]
 [4 6 7 8 9]
 [1 6 6 7 7]
 [1 1 2 2 6]
 [1 2 3 5 7]]
[[6 1 2 1 1]
 [7 1 1 1 2]
 [7 3 6 2 2]
 [8 6 7 5 4]
 [9 7 9 9 6]]
[[1 2 1 9 9]
 [4 6 7 8 9]
 [1 6 6 7 7]
 [1 1 2 2 6]
 [1 2 3 5 7]]


In [200]:
#배열 파일에서 입출력
a2 = np.random.randint(1, 10, size=(5,5))
print(a2)
np.save("a", a2)


[[9 5 4 7 1]
 [4 8 3 5 6]
 [6 1 4 2 2]
 [1 3 9 7 5]
 [9 8 6 5 9]]


In [201]:
!ls #바이너리 파일 사람은 읽ㅇ을 수 없어요

a.npy  sample_data


In [203]:
b2 = np.random.randint(1, 10, size= (5,5))
print(b2)
np.savez("ab", a2, b2)


[[4 5 4 4 9]
 [1 9 4 9 7]
 [3 6 7 2 8]
 [4 9 4 2 7]
 [9 4 7 9 8]]


In [204]:
!ls

ab.npz	a.npy  sample_data


In [205]:
npy = np.load("a.npy")
print(npy) #처음 a2를 불러와

[[9 5 4 7 1]
 [4 8 3 5 6]
 [6 1 4 2 2]
 [1 3 9 7 5]
 [9 8 6 5 9]]


In [207]:
npz = np.load("ab.npz")
print(npz.files)
print(npz['arr_0'])
print(npz['arr_1'])

['arr_0', 'arr_1']
[[9 5 4 7 1]
 [4 8 3 5 6]
 [6 1 4 2 2]
 [1 3 9 7 5]
 [9 8 6 5 9]]
[[4 5 4 4 9]
 [1 9 4 9 7]
 [3 6 7 2 8]
 [4 9 4 2 7]
 [9 4 7 9 8]]


In [209]:
print(a2)
np.savetxt("a.csv",a2, delimiter=',') #comma seperated values

[[9 5 4 7 1]
 [4 8 3 5 6]
 [6 1 4 2 2]
 [1 3 9 7 5]
 [9 8 6 5 9]]


In [211]:
!ls

ab.npz	a.csv  a.npy  sample_data


In [212]:
!cat a.csv #실수 형태로 출력(datatype은 저장을 할 수 없다)

9.000000000000000000e+00,5.000000000000000000e+00,4.000000000000000000e+00,7.000000000000000000e+00,1.000000000000000000e+00
4.000000000000000000e+00,8.000000000000000000e+00,3.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00
6.000000000000000000e+00,1.000000000000000000e+00,4.000000000000000000e+00,2.000000000000000000e+00,2.000000000000000000e+00
1.000000000000000000e+00,3.000000000000000000e+00,9.000000000000000000e+00,7.000000000000000000e+00,5.000000000000000000e+00
9.000000000000000000e+00,8.000000000000000000e+00,6.000000000000000000e+00,5.000000000000000000e+00,9.000000000000000000e+00


In [215]:
csv = np.loadtxt("a.csv", delimiter=',') #구분자를 지정해준다
print(csv) #정상적으로 나타남

[[9. 5. 4. 7. 1.]
 [4. 8. 3. 5. 6.]
 [6. 1. 4. 2. 2.]
 [1. 3. 9. 7. 5.]
 [9. 8. 6. 5. 9.]]


In [218]:
print(b2)
np.savetxt("b.csv", b2, delimiter=',', fmt='%.2e', header = 'c1, c2, c3, c4, c5') #소수점

[[4 5 4 4 9]
 [1 9 4 9 7]
 [3 6 7 2 8]
 [4 9 4 2 7]
 [9 4 7 9 8]]


In [220]:
!cat b.csv

# c1, c2, c3, c4, c5
4.00e+00,5.00e+00,4.00e+00,4.00e+00,9.00e+00
1.00e+00,9.00e+00,4.00e+00,9.00e+00,7.00e+00
3.00e+00,6.00e+00,7.00e+00,2.00e+00,8.00e+00
4.00e+00,9.00e+00,4.00e+00,2.00e+00,7.00e+00
9.00e+00,4.00e+00,7.00e+00,9.00e+00,8.00e+00


In [221]:
csv = np.loadtxt("b.csv", delimiter=',')
print(csv)

[[4. 5. 4. 4. 9.]
 [1. 9. 4. 9. 7.]
 [3. 6. 7. 2. 8.]
 [4. 9. 4. 2. 7.]
 [9. 4. 7. 9. 8.]]
